version: 2
jobs:
  prep:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: |
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run:
            name: Install Dependencies
            command: npm ci

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - persist_to_workspace:
          root: ./
          paths:
            - .

  lint:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Lint
          command: npm run lint -- --format junit --output-file ./reports/eslint/results.xml
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
  build:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Build
          command: |
            npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  tests:
    docker:
      - image: circleci/node:12-stretch-browsers
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Unit Tests
          command: npm run test:single -- --runInBand
          when: always
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
      - run:
          name: Report Coverage
          command: bash <(curl -s https://codecov.io/bash)
  publish:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Calculate Version
          command: npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
      - run:
          name: Publish
          command: ./scripts/release.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - prep
      - lint:
          context: 6rs-public-npm
          requires:
            - prep
      - build:
          context: 6rs-public-npm
          requires:
            - prep
      - tests:
          context: 6rs-public-npm
          requires:
            - prep
      - publish:
          context: 6rs-public-npm
          requires:
            - prep
            - lint
            - build
            - tests
          filters:
            branches:
              only: master
